Repository Kusitms-29th-MeetUp-H/Back, pull requests merged in 2024-05, with the labels that each got.

#2 [Socket]:#1 기본세팅
  socket/build.gradle
  socket/src/main/java/Backend/socket/domain/chat/application/controller/ChatController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/request/ChatListRequestDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/request/ChatMessageListRequestDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/request/ChatMessageRequestDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatListResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatMessageElementResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatMessageListResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatMessageResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatUserResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/SendMessageResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/UserChatResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/ChatService.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/RedisSubscriber.java
  socket/src/main/java/Backend/socket/domain/chat/domain/Chat.java
  socket/src/main/java/Backend/socket/domain/chat/domain/ChatContent.java
  socket/src/main/java/Backend/socket/domain/chat/domain/ChatUser.java
  socket/src/main/java/Backend/socket/domain/chat/domain/User.java
  socket/src/main/java/Backend/socket/domain/chat/repository/ChatRepository.java
  socket/src/main/java/Backend/socket/domain/chat/repository/UserRepository.java
  socket/src/main/java/Backend/socket/global/common/AuthenticationInterceptor.java
  socket/src/main/java/Backend/socket/global/common/JwtProvider.java
  socket/src/main/java/Backend/socket/global/common/MessageSuccessCode.java
  socket/src/main/java/Backend/socket/global/common/MessageSuccessResponse.java
  socket/src/main/java/Backend/socket/global/error/ErrorCode.java
  socket/src/main/java/Backend/socket/global/error/dto/ErrorBaseResponse.java
  socket/src/main/java/Backend/socket/global/error/handler/MessageErrorHandler.java
  socket/src/main/java/Backend/socket/global/error/httpException/BusinessException.java
  socket/src/main/java/Backend/socket/global/error/httpException/InvalidValueException.java
  socket/src/main/java/Backend/socket/global/error/httpException/UnauthorizedException.java
  socket/src/main/java/Backend/socket/global/error/socketException/BusinessException.java
  socket/src/main/java/Backend/socket/global/error/socketException/EntityNotFoundException.java
  socket/src/main/java/Backend/socket/global/error/socketException/UnauthorizedException.java
  socket/src/main/java/Backend/socket/infra/config/MongoDbConfig.java
  socket/src/main/java/Backend/socket/infra/config/RedisConfig.java
  socket/src/main/java/Backend/socket/infra/config/SocketConfig.java
  socket/src/main/java/Backend/socket/infra/config/SocketSecurityConfig.java
  socket/src/main/java/Backend/socket/infra/config/WebConfig.java
  socket/src/main/java/Backend/socket/infra/config/auth/ExceptionHandlerFilter.java
  socket/src/main/java/Backend/socket/infra/config/auth/JwtAuthenticationEntryPoint.java
  socket/src/main/java/Backend/socket/infra/config/auth/JwtAuthenticationFilter.java
  socket/src/main/java/Backend/socket/infra/config/auth/SecurityConfig.java
  socket/src/main/java/Backend/socket/infra/config/auth/UserAuthentication.java
  socket/src/main/java/Backend/socket/infra/config/auth/UserId.java
  socket/src/main/java/Backend/socket/infra/config/auth/UserIdArgumentResolver.java
Labels: chore

#23 [Socket] #1 엔티티 수정
  Main/src/main/java/com/kusitms29/backendH/global/common/HealthCheckApiController.java
  socket/src/main/java/Backend/socket/domain/chat/domain/Gender.java
  socket/src/main/java/Backend/socket/domain/chat/domain/Language.java
  socket/src/main/java/Backend/socket/domain/chat/domain/SyncType.java
  socket/src/main/java/Backend/socket/domain/chat/domain/User.java
  socket/src/main/java/Backend/socket/global/common/BaseEntity.java
Labels: chore

#28 [Main]: #27 엔티티 수정
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  Main/src/main/java/com/kusitms29/backendH/domain/category/domain/Category.java
  Main/src/main/java/com/kusitms29/backendH/domain/category/domain/Type.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/domain/Comment.java
  Main/src/main/java/com/kusitms29/backendH/domain/participation/application/controller/ParticipationController.java
  Main/src/main/java/com/kusitms29/backendH/domain/participation/application/service/ParticipationService.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/domain/Post.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/domain/PostType.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/SyncController.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/service/SyncService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/Sync.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/SyncCategory.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/domain/User.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/domain/UserCategory.java
Labels: docs

#32 [Main]: #31 싱크 추천 api 구현 및 엔티티 수정
  Main/src/main/java/com/kusitms29/backendH/domain/participation/domain/service/ParticipationManager.java
  Main/src/main/java/com/kusitms29/backendH/domain/participation/repository/ParticipationRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/SyncManageController.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/dto/response/SyncInfoResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/service/SyncManageService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/service/SyncService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/Sync.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/SyncCategory.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/service/SyncReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/repository/SyncRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/domain/User.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/domain/service/UserCategoryManager.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/domain/service/UserCategoryReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/domain/service/UserReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/repository/UserCategoryRepository.java
Labels: feat

#40 [Main]: #31 싱크(메인) api 들 구현
  Main/build.gradle
  Main/src/main/java/com/kusitms29/backendH/domain/category/domain/Type.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/map/GeoLocation.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/map/GeoLocationResponse.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/map/GeoLocationService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/SyncManageController.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/dto/request/SyncInfoRequestDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/service/SyncManageService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/SyncType.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/service/SyncReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/repository/SyncRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/ip/IpService.java
  Main/src/main/java/com/kusitms29/backendH/global/error/ErrorCode.java
  Main/src/main/java/com/kusitms29/backendH/global/error/exception/ListUtils.java
Labels: feat, fix

#48 [Main]: #45 싱크 상세 및 그래프 데이터 api 구현
  Main/src/main/java/com/kusitms29/backendH/domain/participation/domain/service/ParticipationReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/participation/repository/ParticipationRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/SyncDetailController.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/dto/response/GraphElement.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/dto/response/SyncDetailResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/dto/response/SyncGraphResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/service/SyncManager.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/service/SyncReader.java
  Main/src/main/java/com/kusitms29/backendH/global/error/ErrorCode.java
Labels: feat

#55 [Main]: #49 커뮤니티 api
  Main/src/main/java/com/kusitms29/backendH/domain/clova/papago/PapagoController.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/papago/PapagoService.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/papago/detection/LanguageDetectionRequest.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/papago/detection/LanguageDetectionResponse.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/papago/translation/TextTranslationRequest.java
  Main/src/main/java/com/kusitms29/backendH/domain/clova/papago/translation/TextTranslationResponse.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/application/controller/CommentController.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/application/controller/dto/request/CommentCreateRequestDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/application/controller/dto/response/CommentCreateResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/application/controller/dto/response/CommentResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/application/service/CommentService.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/domain/Comment.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/repository/CommentPagingRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/repository/CommentRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/commentLike/application/controller/CommentLikeController.java
  Main/src/main/java/com/kusitms29/backendH/domain/commentLike/application/service/CommentLikeService.java
  Main/src/main/java/com/kusitms29/backendH/domain/commentLike/repository/CommentLikeRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/controller/dto/PostController.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/controller/dto/request/PostCalculateDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/controller/dto/request/PostCreateRequestDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/controller/dto/response/PostCreateResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/controller/dto/response/PostDetailResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/controller/dto/response/PostResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/controller/dto/response/PostSearchResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/service/PostSearchService.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/application/service/PostService.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/domain/PostImage.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/repository/PostImageRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/repository/PostPagingRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/repository/PostRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/postLike/application/controller/PostLikeController.java
  Main/src/main/java/com/kusitms29/backendH/domain/postLike/application/service/PostLikeService.java
  Main/src/main/java/com/kusitms29/backendH/domain/postLike/repository/PostLikeRepository.java
  Main/src/main/java/com/kusitms29/backendH/global/error/ErrorCode.java
  Main/src/main/java/com/kusitms29/backendH/infra/config/AwsS3Service.java
Labels: feat

#56 [Main]: #45 싱크 상세 api 구현
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/SyncDetailController.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/SyncManageController.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/controller/dto/response/SyncDetailResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/application/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/Sync.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/service/SyncManager.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/domain/service/SyncReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/repository/SyncRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/syncReview/application/controller/SyncReviewController.java
  Main/src/main/java/com/kusitms29/backendH/domain/syncReview/application/service/SyncReviewService.java
  Main/src/main/java/com/kusitms29/backendH/domain/syncReview/application/service/dto/SyncReviewResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/syncReview/domain/repository/SyncReviewRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/syncReview/domain/service/SyncReviewReader.java
  Main/src/main/java/com/kusitms29/backendH/global/common/Util.java
  Main/src/main/java/com/kusitms29/backendH/infra/config/SecurityConfig.java
Labels: feat

#67 [Feat]: #66 마이페이지 api 구현
  Main/src/main/java/com/kusitms29/backendH/api/user/controller/MyPageController.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/request/CreateReviewRequest.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/response/CreateReviewResponse.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/response/UserInfoResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/entity/Sync.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/entity/SyncReview.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/repository/FavoriteSyncRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/repository/SyncRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/FavoriteSyncReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/SyncReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/SyncReviewAppender.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/entity/User.java
Labels: feat

#68 [feat]: Main #66 마이페이지 api 구현
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
Labels: feat

#73 [feat]: Main #66 프로필 수정 api 구현
  Main/src/main/java/com/kusitms29/backendH/api/user/controller/MyPageController.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/request/EditProfileRequest.java
  Main/src/main/java/com/kusitms29/backendH/domain/category/entity/UserCategory.java
  Main/src/main/java/com/kusitms29/backendH/domain/category/repository/UserCategoryRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/category/service/UserCategoryModifier.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/entity/User.java
Labels: feat

#81 [fix]: Main #49 커뮤니티 api : 게시물 이미지 없이 생성
  Main/src/main/java/com/kusitms29/backendH/api/community/controller/CommunityController.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/PostService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/controller/SyncManageController.java
Labels: fix

#82 [feat]:Socket 단톡방 리스트 불러오기 추가
  socket/src/main/java/Backend/socket/domain/chat/application/controller/RoomController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/RoomChatResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/RoomListResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/RoomService.java
  socket/src/main/java/Backend/socket/domain/chat/domain/Room.java
Labels: feat

#92 [feat]:Socket 이미지 보내기
  socket/build.gradle
  socket/src/main/java/Backend/socket/domain/chat/application/controller/ChatController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/RoomController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/request/ChatMessageRoomRequestDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatMessageElementResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/ChatService.java
  socket/src/main/java/Backend/socket/domain/chat/domain/Room.java
  socket/src/main/java/Backend/socket/global/error/ErrorCode.java
  socket/src/main/java/Backend/socket/global/error/httpException/InternalServerException.java
  socket/src/main/java/Backend/socket/infra/external/AwsService.java
Labels: feat

#97 [feat]:Socket 이미지 보내기 테스트
  socket/build.gradle
  socket/src/main/java/Backend/socket/domain/chat/application/controller/ChatController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/RoomController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/request/ChatMessageRoomRequestDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/ChatService.java
  socket/src/main/java/Backend/socket/global/common/HealthCheck.java
  socket/src/main/java/Backend/socket/global/common/image.java
  socket/src/main/java/Backend/socket/infra/external/AwsService.java
Labels: feat

#105 [Main]: #49 커뮤니티 댓글 신고 api
  Main/src/main/java/com/kusitms29/backendH/api/community/service/CommentService.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/repository/ReplyRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/service/ReplyModifier.java
Labels: fix

#106 [Main]: #93 api 수정
  Main/src/main/java/com/kusitms29/backendH/api/user/controller/MyPageController.java
  Main/src/main/java/com/kusitms29/backendH/api/user/controller/OnBoardingController.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/OnBoardingService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/request/OnBoardingRequestDto.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/response/OnBoardingResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/response/UserInfoResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/response/schoolEmail/CalloutErrorResponse.java
  Main/src/main/java/com/kusitms29/backendH/infra/external/UniversityClient.java
Labels: feat

#107 [Main]: #49 fcmtoken redis 설정
  Main/src/main/java/com/kusitms29/backendH/api/user/service/AuthService.java
  Main/src/main/java/com/kusitms29/backendH/infra/config/RedisConfig.java
Labels: bug, fix

#108 [Main]: #70 알림 채널 연결
  Main/src/main/java/com/kusitms29/backendH/api/user/service/AuthService.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/repository/SyncRepository.java
  Main/src/main/java/com/kusitms29/backendH/infra/external/fcm/service/PushNotificationService.java
  Main/src/main/java/com/kusitms29/backendH/infra/external/fcm/service/dto/NotificationDto.java
Labels: feat, fix

#109 [Main]: #70 푸쉬 알림 api 수정
  Main/src/main/java/com/kusitms29/backendH/infra/external/fcm/service/PushNotificationService.java
  Main/src/main/java/com/kusitms29/backendH/infra/external/fcm/service/dto/NotificationDto.java
Labels: fix

#110 [Main]: #70 채팅 알림 구현
  Main/src/main/java/com/kusitms29/backendH/api/notification/service/NotificationHistoryService.java
  Main/src/main/java/com/kusitms29/backendH/infra/external/fcm/service/dto/NotificationDto.java
  socket/.gitignore
  socket/build.gradle
  socket/src/main/java/Backend/socket/domain/chat/application/service/ChatService.java
  socket/src/main/java/Backend/socket/domain/chat/domain/notification/entity/NotificationHistory.java
  socket/src/main/java/Backend/socket/domain/chat/domain/notification/entity/NotificationType.java
  socket/src/main/java/Backend/socket/domain/chat/domain/notification/entity/TopCategory.java
  socket/src/main/java/Backend/socket/domain/chat/domain/notification/repository/NotificationHistoryRepository.java
  socket/src/main/java/Backend/socket/global/error/ErrorCode.java
  socket/src/main/java/Backend/socket/infra/config/FCMConfig.java
  socket/src/main/java/Backend/socket/infra/external/fcm/MessageTemplate.java
  socket/src/main/java/Backend/socket/infra/external/fcm/repository/FCMTokenRepository.java
  socket/src/main/java/Backend/socket/infra/external/fcm/service/PushNotificationService.java
  socket/src/main/java/Backend/socket/infra/external/fcm/service/dto/NotificationDto.java
Labels: feat

#125 [fix] Main 연동 중 수정사항
  Main/src/main/java/com/kusitms29/backendH/api/sync/controller/SyncDetailController.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncAssociateInfoResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncDetailResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncInfoResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/api/user/controller/MyPageController.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/request/EditProfileReq.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/repository/ParticipationRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/ParticipationAppender.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/ParticipationManager.java
Labels: fix

#127 [fix] Main 마이페이지 변경 및 북마크 req 형식 변경
  Main/src/main/java/com/kusitms29/backendH/api/sync/controller/SyncDetailController.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/request/SyncBookmarkRequestDto.java
  Main/src/main/java/com/kusitms29/backendH/api/user/controller/MyPageController.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/request/EditProfileRequest.java
Labels: fix

#128 [fix]:Main 마이 페이지 오타 수정
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
Labels: fix

#129 [chore]Socket config 변경 및 채팅 dto 변경
  socket/src/main/java/Backend/socket/domain/chat/application/controller/ChatController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/request/ChatMessageRoomRequestDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatMessageElementResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/RoomChatResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/ChatService.java
  socket/src/main/java/Backend/socket/infra/config/RedisConfig.java
Labels: chore

#130 [chore]Socket cicd flow 변경
  .github/workflows/socket-service-cicd.yml
Labels: chore

#131 [chore]Socket cicd flow 변경
  .github/workflows/socket-service-cicd.yml
Labels: chore

#138 [refactor]Socket fcm 주석처리
  socket/src/main/java/Backend/socket/infra/config/RedisConfig.java
Labels: refactor

#148 [fix]Main api 연동 수정사항 적용
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncDetailResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/dto/response/UserInfoResponseDto.java
Labels: fix

#149 [fix]Main 싱크 상세 응답값 수정
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncDetailResponseDto.java
Labels: fix

#150 [fix]Main 그래프 비교값 수정
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/SyncManager.java
Labels: fix

#151 [fix]:Main Papago 번역 main에 적용
  Main/src/main/java/com/kusitms29/backendH/api/sync/controller/SyncMainController.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/request/SyncInfoRequestDto.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncAssociateInfoResponse.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncInfoResponse.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/entity/ChatContent.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/entity/Room.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/repository/RoomRepository.java
  Main/src/main/java/com/kusitms29/backendH/global/common/ChatReq.java
  Main/src/main/java/com/kusitms29/backendH/global/common/HealthCheckApiController.java
  Main/src/main/java/com/kusitms29/backendH/infra/config/MongoDbConfig.java
  Main/src/main/java/com/kusitms29/backendH/infra/utils/TranslateUtil.java
Labels: fix

#153 [Main]: #152 리펙토링
  Main/src/main/java/com/kusitms29/backendH/api/community/service/CommentLikeService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/CommentService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/PostLikeService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/PostService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/ReplyLikeService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/ReplyService.java
  Main/src/main/java/com/kusitms29/backendH/api/notification/service/NotificationService.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/entity/Comment.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/entity/CommentLike.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/entity/Reply.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/entity/ReplyLike.java
  Main/src/main/java/com/kusitms29/backendH/domain/notification/repository/NotificationRepository.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/entity/Post.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/entity/PostImage.java
  Main/src/main/java/com/kusitms29/backendH/domain/post/entity/PostLike.java
Labels: refactor

#154 [feat]:Main 번역 프롬프트 생성 및 적용
  Main/src/main/java/com/kusitms29/backendH/api/sync/controller/SyncMainController.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncService.java
  Main/src/main/java/com/kusitms29/backendH/global/common/HealthCheckApiController.java
  Main/src/main/java/com/kusitms29/backendH/infra/config/TranslateConfig.java
  Main/src/main/java/com/kusitms29/backendH/infra/utils/TranslateUtil.java
  Main/src/main/resources/prompt.properties
Labels: feat

#156 [fix]Socket 채팅방 방장 구별 dto 추가
  socket/src/main/java/Backend/socket/domain/chat/application/controller/ChatController.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatMessageElementResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/ChatUserResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/RoomChatResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/RoomMessageElementResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/ChatService.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/Formatter.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/RoomService.java
  socket/src/main/java/Backend/socket/domain/chat/domain/Room.java
Labels: fix

#158 [fix]:Main 방 생성시 방장 정보 추가
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/entity/Room.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/service/RoomAppender.java
Labels: fix

#160 [fix]Socket image 필드 추가
  socket/src/main/java/Backend/socket/domain/chat/application/controller/dto/response/RoomMessageElementResponseDto.java
  socket/src/main/java/Backend/socket/domain/chat/application/service/ChatService.java
  socket/src/main/java/Backend/socket/domain/chat/domain/ChatContent.java
Labels: fix

#161 [refactor]: Main #159 코드 정리 및 불필요 코드 삭제
  Main/src/main/java/com/kusitms29/backendH/api/community/service/CommentLikeService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/CommentService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/PostLikeService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/PostSearchService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/PostService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/ReplyLikeService.java
  Main/src/main/java/com/kusitms29/backendH/api/community/service/ReplyService.java
  Main/src/main/java/com/kusitms29/backendH/api/notification/service/NotificationHistoryService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/AuthService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/MyPageService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/OnBoardingService.java
  Main/src/main/java/com/kusitms29/backendH/api/user/service/UserService.java
  Main/src/main/java/com/kusitms29/backendH/domain/category/service/UserCategoryManager.java
  Main/src/main/java/com/kusitms29/backendH/domain/category/service/UserCategoryReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/comment/service/CommentReader.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/SyncManager.java
  Main/src/main/java/com/kusitms29/backendH/domain/user/service/UserReader.java
  Main/src/main/java/com/kusitms29/backendH/global/common/HealthCheckApiController.java
  Main/src/main/java/com/kusitms29/backendH/infra/external/fcm/service/PushNotificationService.java
Labels: refactor

#164 [fix]:Main 채팅방 개설시 이미지 추가
  Main/src/main/java/com/kusitms29/backendH/domain/chat/entity/ChatContent.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/service/RoomAppender.java
  Main/src/main/java/com/kusitms29/backendH/global/common/HealthCheckApiController.java
Labels: fix

#165 [fix]:Main 채팅방 유저 추가 로직 수정
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/service/RoomAppender.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/service/RoomReader.java
  Main/src/main/java/com/kusitms29/backendH/global/common/HealthCheckApiController.java
Labels: fix

#169 [fix]:Socket 수정
  socket/src/main/java/Backend/socket/infra/config/auth/JwtAuthenticationFilter.java
  socket/src/main/java/Backend/socket/infra/config/auth/SecurityConfig.java
Labels: fix

#170 [refactor]:Main 코드 정리
  Main/build.gradle
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncDetailService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/SyncService.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/request/SyncInfoRequestDto.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncAssociateInfoResponse.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncDetailResponseDto.java
  Main/src/main/java/com/kusitms29/backendH/api/sync/service/dto/response/SyncInfoResponse.java
  Main/src/main/java/com/kusitms29/backendH/domain/chat/service/RoomAppender.java
  Main/src/main/java/com/kusitms29/backendH/domain/sync/service/SyncReader.java
Labels: refactor
